#!/bin/bash

# run.sh: runs the actual submission

# python3 client/fake_test_driver.py & python3 server/test_driver.py 
cat - | python3 server/test_driver.py & sleep 1 && python3 client/fake_test_driver.py